### ISSUE TITLE
Align clade labels in phylogeny

### ISSUE THREAD

**Issue by lauracespedesarias** [liamrevell/phytools#26]
Hello Liam and all,

I am using the cladelabels function in phytools to annotate clades in a cladogram. I want to annotate several clades but I have found difficult to have the lines (produce by cladelabels) aligned between clades. I figured this is because I am not using the 'offset' argument correctly. Is there a way to have all these perfectly aligned? This would make the figure much better. Thank you very much for your help with this.

Best,

Laura Céspedes

**Comment by liamrevell** [comment]
Hi Laura. Can you send me an example with code?

**Comment by lauracespedesarias** [comment]
Hi Liam,
Thank you very much for your answer. I ended up using 'geomclade' from the ggtree package to do this and therefore do not have the code for this now. Thanks anyway.
Best,
Laura

**Comment by AgustinPardo** [comment]
I have the same issue!

**Comment by liamrevell** [comment]
I believe that offset is calculated from the height of the tips of the tree. If the tree is ultrametric then cladelabels with the same offset will be aligned. If not, you need to compute the difference between the height of the highest tip in your clade and the total length of the tree in order to fix offset values that cause the clade labels to align.
