### ISSUE TITLE
Problems installing in R version 3.3.2 (CentOS 7)

### ISSUE THREAD

**Issue by agroppi** [liamrevell/phytools#63]
Hi,
I have the following errors when trying to install phytools in R 3.3.2 : 

```install.packages("phytools",dependencies=TRUE)```
...
```
The downloaded source packages are in
        ‘/tmp/Rtmp4OdBCz/downloaded_packages’
Warning messages:
1: In install.packages("phytools", dependencies = TRUE) :
  installation of package ‘magick’ had non-zero exit status
2: In install.packages("phytools", dependencies = TRUE) :
  installation of package ‘rgl’ had non-zero exit status
3: In install.packages("phytools", dependencies = TRUE) :
  installation of package ‘animation’ had non-zero exit status
4: In install.packages("phytools", dependencies = TRUE) :
  installation of package ‘phytools’ had non-zero exit status
```
Is it a problem with my R version ?

Thanks

**Comment by liamrevell** [comment]
Yes, this is likely due to your R version. You have a few choices:
1) Update R. This is what I would recommend.
2) Try to to install phytools without updating dependencies, i.e., install.packages("phytools",dependencies=FALSE).
3) Try to install each of the failing dependent packages separately, i.e., install.packages("magick") & so on.
If (2) & (3) fail, you may have no choice but to update R. Updating to at least >=3.6 should be fine.

**Comment by KlausVigo** [comment]
Hi @agroppi, 
it is probably worth to update R (4.0 is the current version), but for rgl you need mesa drivers installed (on debian this could be done with aptitude install libgl1-mesa-dev libglu1-mesa-dev, there should be similar rpm for CentOS) and for magick you the ImageMagick installed. See the README and SystemRequirements on the CRAN page to these packages.
